name: Check latest librespot version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          wget -q http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
          tar -xf APKINDEX.tar.gz
          grep -A1 '^P:librespot$' APKINDEX | grep '^V:' | sed 's/^V://' | tee .version
      - name: Check for modified files
        id: git-check
        run: echo modified=$([ -z "`git status .version --porcelain`" ] && echo "false" || echo "true") >> $GITHUB_OUTPUT
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'github-action@github.com'
          git add .version
          git commit -m "New librespot version"
          git push
